name: Test Optional Dependencies

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-without-optional-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install minimal dependencies (no extras)
      run: |
        python -m pip install --upgrade pip
        # Install without any extras to test NotInstalled behavior
        pip install -e .
    
    - name: Run test
      run: |
        python checks/test_playwright_not_installed.py
